### ISSUE TITLE
sqlite 3.46 package broken?

### ISSUE THREAD

**Issue by jamartinh** [conda-forge/sqlite-feedstock#108]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

From today when running update --all in a cond env either with mamba or conda I am having errors both on windows and linux with executing Ipython and JupyterLab with issues with sqlite3

On linux is a.so error
On Windows an import DLL load failed

```

$ ipython
Traceback (most recent call last):
  File "/data/conda/envs/python312/bin/ipython", line 6, in <module>
    from IPython import start_ipython
  File "/data/conda/envs/python312/lib/python3.12/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/data/conda/envs/python312/lib/python3.12/site-packages/IPython/terminal/embed.py", line 15, in <module>
    from IPython.core.interactiveshell import DummyMod, InteractiveShell
  File "/data/conda/envs/python312/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 110, in <module>
    from IPython.core.history import HistoryManager
  File "/data/conda/envs/python312/lib/python3.12/site-packages/IPython/core/history.py", line 10, in <module>
    import sqlite3
  File "/data/conda/envs/python312/lib/python3.12/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/data/conda/envs/python312/lib/python3.12/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: /data/conda/envs/python312/lib/python3.12/lib-dynload/_sqlite3.cpython-312-x86_64-linux-gnu.so: undefined symbol: sqlite3_deserialize

$ conda install sqlite=3.45
Channels:
 - defaults
 - conda-forge
 - pytorch
 - nvidia
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /data/conda/envs/python312

  added / updated specs:
    - sqlite=3.45


The following packages will be SUPERSEDED by a higher-priority channel:

  sqlite              conda-forge::sqlite-3.46.0-h6d4b2fc_0 --> pkgs/main::sqlite-3.45.3-h5eee18b_0


Proceed ([y]/n)?


Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(python312) [r107333@z0euw1lptmx515 deploy]$ ipython
Python 3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:38:13) [GCC 12.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.26.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: exit

```

### Installed packages

```shell
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
absl-py                   2.1.0           py312h06a4308_0
aiohttp                   3.9.5           py312h5eee18b_0
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
annotated-types           0.7.0              pyhd8ed1ab_0    conda-forge
anyio                     4.4.0              pyhd8ed1ab_0    conda-forge
argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py312h5eee18b_0
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.4           py312h06a4308_0
async-timeout             4.0.3           py312h06a4308_0
attrs                     23.2.0             pyh71513ae_0    conda-forge
babel                     2.14.0             pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.3          py312h06a4308_0
blas                      2.122                  openblas    conda-forge
blas-devel                3.9.0           22_linux64_openblas    conda-forge
bleach                    6.1.0              pyhd8ed1ab_0    conda-forge
blinker                   1.8.2              pyhd8ed1ab_0    conda-forge
bottleneck                1.4.0           py312h085067d_1    conda-forge
brotli                    1.1.0                hd590300_1    conda-forge
brotli-bin                1.1.0                hd590300_1    conda-forge
brotli-python             1.1.0           py312h30efb56_1    conda-forge
bzip2                     1.0.8                h5eee18b_6
c-ares                    1.32.0               h4ab18f5_0    conda-forge
ca-certificates           2024.7.4             hbcca054_0    conda-forge
cached-property           1.5.2                      py_0
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                5.3.3           py312h06a4308_0
certifi                   2024.7.4        py312h06a4308_0
cffi                      1.16.0          py312h5eee18b_1
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7           py312h06a4308_0
cloudpickle               3.0.0              pyhd8ed1ab_0    conda-forge
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.1           py312h8572e83_0    conda-forge
cpprb                     11.0.0                   pypi_0    pypi
cuda-cudart               12.5.82              he02047a_0    conda-forge
cuda-cudart_linux-64      12.5.82              h85509e4_0    conda-forge
cuda-nvrtc                12.5.82              he02047a_0    conda-forge
cuda-nvtx                 12.5.82              he02047a_0    conda-forge
cuda-version              12.5                 hd4f0392_3    conda-forge
cudnn                     8.9.7.29             h092f7fd_3    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyh6d0b6a4_7
debugpy                   1.8.2           py312h7070661_0    conda-forge
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
deprecated                1.2.14             pyh1a96a4e_0    conda-forge
distributedrl             0.1                       dev_0    <develop>
entrypoints               0.4             py312h06a4308_0
etils                     1.9.2              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.0           py312h06a4308_0
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
expat                     2.6.2                h6a678d5_0
factoria                  1.0                       dev_0    <develop>
farama-notifications      0.0.4           py312h06a4308_0
filelock                  3.15.4             pyhd8ed1ab_0    conda-forge
flask                     3.0.3           py312h06a4308_0
fonttools                 4.53.1          py312h41a817b_0    conda-forge
freetype                  2.12.1               h4a9f257_0
frozenlist                1.4.1           py312h98912ed_0    conda-forge
fsspec                    2024.6.1           pyhff2d567_0    conda-forge
glfw                      3.4                  hd590300_0    conda-forge
gmp                       6.3.0                hac33072_2    conda-forge
gmpy2                     2.1.5           py312h1d5cde6_1    conda-forge
google-api-core           2.19.1                   pypi_0    pypi
google-auth               2.32.0                   pypi_0    pypi
google-cloud-core         2.4.1                    pypi_0    pypi
google-cloud-storage      2.17.0                   pypi_0    pypi
google-crc32c             1.5.0           py312h5eee18b_0
google-resumable-media    2.7.1                    pypi_0    pypi
googleapis-common-protos  1.63.2             pyhd8ed1ab_0    conda-forge
grpcio                    1.62.2          py312hb06c811_0    conda-forge
gymnasium                 0.29.1          py312h8da182e_1    conda-forge
h11                       0.14.0          py312h06a4308_0
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
h5py                      3.11.0          py312h34c39bb_0
hdf5                      1.12.1               h2b7332f_3
hpack                     4.0.0                      py_0
httpcore                  1.0.5              pyhd8ed1ab_0    conda-forge
httpx                     0.27.0             pyhd8ed1ab_0    conda-forge
hyperframe                6.0.1              pyhd3eb1b0_0
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.7             py312h06a4308_0
imageio                   2.34.2             pyh12aca89_0    conda-forge
importlib-metadata        8.0.0              pyha770c72_0    conda-forge
importlib_metadata        8.0.0                hd8ed1ab_0    conda-forge
importlib_resources       6.4.0           py312h06a4308_0
ipykernel                 6.29.5             pyh3099207_0    conda-forge
ipython                   8.26.0             pyh707e725_0    conda-forge
ipywidgets                8.1.3              pyhd8ed1ab_0    conda-forge
itsdangerous              2.2.0           py312h06a4308_0
jax-jumpy                 1.0.0           py312h06a4308_0
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4           py312h06a4308_0
joblib                    1.4.2           py312h06a4308_0
json5                     0.9.25             pyhd8ed1ab_0    conda-forge
jsonschema                4.23.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.12.1          pyhd8ed1ab_0    conda-forge
jupyter-lsp               2.2.5              pyhd8ed1ab_0    conda-forge
jupyter_client            8.6.2              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2           py312h06a4308_0
jupyter_events            0.10.0          py312h06a4308_0
jupyter_server            2.14.1          py312h06a4308_0
jupyter_server_terminals  0.5.3              pyhd8ed1ab_0    conda-forge
jupyterlab                4.2.3              pyhd8ed1ab_0    conda-forge
jupyterlab_code_formatter 2.2.1           py312h06a4308_0
jupyterlab_pygments       0.3.0              pyhd8ed1ab_1    conda-forge
jupyterlab_server         2.27.2             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.11             pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5           py312h8572e83_1    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.40                 hf3520f5_7    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20240116.2      cxx17_h6a678d5_0
libaec                    1.1.3                h59595ed_0    conda-forge
libblas                   3.9.0           22_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcblas                  3.9.0           22_linux64_openblas    conda-forge
libccd-double             2.1                  h59595ed_3    conda-forge
libcrc32c                 1.1.2                h6a678d5_0
libcublas                 12.5.3.2             he02047a_0    conda-forge
libcufft                  11.2.3.61            he02047a_0    conda-forge
libcurand                 10.3.6.82            he02047a_0    conda-forge
libcurl                   8.8.0                hca28451_1    conda-forge
libcusolver               11.6.3.83            he02047a_0    conda-forge
libcusparse               12.5.1.3             he02047a_0    conda-forge
libdeflate                1.20                 hd590300_0    conda-forge
libedit                   3.1.20230828         h5eee18b_0
libev                     4.33                 h7f8727e_1
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.4                h6a678d5_1
libgcc-ng                 14.1.0               h77fa898_0    conda-forge
libgfortran-ng            14.1.0               h69a702a_0    conda-forge
libgfortran5              14.1.0               hc5f4f2c_0    conda-forge
libgomp                   14.1.0               h77fa898_0    conda-forge
libgrpc                   1.62.2               h15f2491_0    conda-forge
libhwloc                  2.11.1          default_hecaa2ac_1000    conda-forge
libjpeg-turbo             3.0.3                h5eee18b_0
liblapack                 3.9.0           22_linux64_openblas    conda-forge
liblapacke                3.9.0           22_linux64_openblas    conda-forge
libmagma                  2.7.2                h173bb3b_2    conda-forge
libmagma_sparse           2.7.2                h173bb3b_3    conda-forge
libmujoco                 3.1.6                h754e0f8_0    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libnvjitlink              12.5.82              he02047a_0    conda-forge
libopenblas               0.3.27          pthreads_hac2b453_1    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libprotobuf               4.25.3               he621ea3_0
libre2-11                 2023.09.01           h5a48ba9_2    conda-forge
libsodium                 1.0.18               h7b6447c_0
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libssh2                   1.11.0               h251f7ec_0
libstdcxx-ng              14.1.0               hc0a3c3a_0    conda-forge
libtiff                   4.6.0                h1dd3fc0_3    conda-forge
libtorch                  2.3.0           cuda120_h2b0da52_301    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libuv                     1.48.0               hd590300_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.15                 h7f8727e_0
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxkbcommon              1.7.0                h662e7e4_0    conda-forge
libxml2                   2.13.1               hfdd30dd_0
libzlib                   1.2.13               h4ab18f5_6    conda-forge
llvm-openmp               18.1.7               ha31de31_0    conda-forge
lodepng                   20220109             h924138e_0    conda-forge
markdown                  3.6                pyhd8ed1ab_0    conda-forge
markdown-it-py            2.2.0           py312h06a4308_1
markupsafe                2.1.5           py312h98912ed_0    conda-forge
matplotlib-base           3.9.1           py312h9201f00_0    conda-forge
matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
mdurl                     0.1.2                    pypi_0    pypi
minari                    0.4.3                    pypi_0    pypi
mistune                   3.0.2              pyhd8ed1ab_0    conda-forge
mkl                       2023.2.0         h84fe81f_50496    conda-forge
mkl-service               2.4.1           py312h4daa2fd_0    conda-forge
mkl_fft                   1.3.10          py312h8a8eec4_1    conda-forge
mkl_random                1.2.6           py312h233cd48_1    conda-forge
mpc                       1.3.1                hfe3b2da_0    conda-forge
mpfr                      4.2.1                h9458935_1    conda-forge
mpmath                    1.3.0           py312h06a4308_0
mujoco                    3.1.6                ha770c72_0    conda-forge
mujoco-python             3.1.6           py312h8fc6881_0    conda-forge
mujoco-samples            3.1.6                hac33072_0    conda-forge
mujoco-simulate           3.1.6                hac33072_0    conda-forge
multidict                 6.0.5           py312h98912ed_0    conda-forge
munkres                   1.1.4                      py_0
nbclient                  0.10.0             pyhd8ed1ab_0    conda-forge
nbconvert                 7.16.4               hd8ed1ab_1    conda-forge
nbconvert-core            7.16.4             pyhd8ed1ab_1    conda-forge
nbconvert-pandoc          7.16.4               hd8ed1ab_1    conda-forge
nbformat                  5.10.4             pyhd8ed1ab_0    conda-forge
nccl                      2.22.3.1             hbc370b7_0    conda-forge
ncurses                   6.5                  h59595ed_0    conda-forge
nest-asyncio              1.6.0           py312h06a4308_0
networkx                  3.3             py312h06a4308_0
nomkl                     3.0                           0
notebook-shim             0.2.4              pyhd8ed1ab_0    conda-forge
numexpr                   2.10.0          py312hf412c99_100    conda-forge
numpy                     1.26.4          py312h2809609_0
numpy-base                1.26.4          py312he1a6c75_0
openblas                  0.3.27          pthreads_h9eca1d5_1    conda-forge
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openssl                   3.3.1                h4ab18f5_1    conda-forge
overrides                 7.7.0              pyhd8ed1ab_0    conda-forge
packaging                 24.1            py312h06a4308_0
pandas                    2.2.2           py312h526ad5a_0
pandoc                    3.2.1                ha770c72_0    conda-forge
pandocfilters             1.5.0              pyhd3eb1b0_0
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
patsy                     0.5.6           py312h06a4308_0
pexpect                   4.9.0              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    10.3.0          py312hdcec9eb_0    conda-forge
pip                       24.0            py312h06a4308_0
pkgutil-resolve-name      1.3.10          py312h06a4308_1
platformdirs              4.2.2              pyhd8ed1ab_0    conda-forge
polcanet                  1.0.0                     dev_0    <develop>
portion                   2.4.2              pyhd8ed1ab_0    conda-forge
prometheus_client         0.20.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.47             pyha770c72_0    conda-forge
prompt_toolkit            3.0.47               hd8ed1ab_0    conda-forge
proto-plus                1.24.0                   pypi_0    pypi
protobuf                  5.27.2                   pypi_0    pypi
psutil                    6.0.0           py312h9a8786e_0    conda-forge
ptyprocess                0.7.0              pyhd3eb1b0_2
pure_eval                 0.2.2              pyhd3eb1b0_0
pyasn1                    0.6.0                    pypi_0    pypi
pyasn1-modules            0.4.0              pyhd8ed1ab_0    conda-forge
pybind11-abi              4                    hd3eb1b0_1
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pydantic                  2.8.2              pyhd8ed1ab_0    conda-forge
pydantic-core             2.20.1          py312hf008fa9_0    conda-forge
pyglfw                    2.7.0           py312h7900ff3_0    conda-forge
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pyopengl                  3.1.6              pyhd8ed1ab_1    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pyrtpi                    1.0                       dev_0    <develop>
pysocks                   1.7.1           py312h06a4308_0
pythae                    0.1.2              pyhd8ed1ab_1    conda-forge
python                    3.12.3          hab00c5b_0_cpython    conda-forge
python-dateutil           2.9.0post0      py312h06a4308_2
python-fastjsonschema     2.20.0             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7           py312h06a4308_0
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.12                    4_cp312    conda-forge
pytorch                   2.3.0           cuda120_py312h26b3cf7_301    conda-forge
pytorch-gpu               2.3.0           cuda120py312hf72234c_301    conda-forge
pytz                      2024.1          py312h06a4308_0
pyyaml                    6.0.1           py312h5eee18b_0
pyzmq                     26.0.3          py312h8fd38d8_0    conda-forge
qhull                     2020.2               hdb19cb5_2
re2                       2023.09.01           h7f4b329_2    conda-forge
readline                  8.2                  h5eee18b_0
redis-py                  5.0.7              pyhd8ed1ab_0    conda-forge
redis-server              7.2.5                he19d79f_0    conda-forge
referencing               0.35.1             pyhd8ed1ab_0    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4           py312h06a4308_0
rfc3986-validator         0.1.1           py312h06a4308_0
rich                      13.7.1          py312h06a4308_0
rpds-py                   0.19.0          py312hf008fa9_0    conda-forge
rsa                       4.9                      pypi_0    pypi
scikit-learn              1.5.1           py312h775a589_0    conda-forge
scipy                     1.14.0          py312hc2bc53b_1    conda-forge
seaborn                   0.13.2          py312h06a4308_0
seaborn-base              0.13.2             pyhd8ed1ab_0    conda-forge
send2trash                1.8.3              pyh0d859eb_0    conda-forge
setuptools                70.2.0             pyhd8ed1ab_0    conda-forge
shellingham               1.5.4                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1
sleef                     3.5.1                h9b69904_2    conda-forge
sniffio                   1.3.1              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd3eb1b0_0
soupsieve                 2.5             py312h06a4308_0
sqlite                    3.45.3               h5eee18b_0
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
statsmodels               0.14.2          py312ha883a20_0
sympy                     1.12.1          pypyh2585a3b_103    conda-forge
tabulate                  0.9.0           py312h06a4308_0
tbb                       2021.8.0             hdb19cb5_0
tensorboard               2.17.0             pyhd8ed1ab_0    conda-forge
tensorboard-data-server   0.7.0           py312h52d8a92_0
tensorboardx              2.6.2.2            pyhd8ed1ab_0    conda-forge
terminado                 0.18.1             pyh0d859eb_0    conda-forge
threadpoolctl             3.5.0           py312he106c6f_0
tinycss2                  1.3.0              pyhd8ed1ab_0    conda-forge
tinyxml2                  10.0.0               h59595ed_0    conda-forge
tk                        8.6.14               h39e8969_0
tomli                     2.0.1           py312h06a4308_1
torchvision               0.18.1          cuda120py312hb04d961_1    conda-forge
tornado                   6.4.1           py312h5eee18b_0
tqdm                      4.66.4          py312he106c6f_0
traitlets                 5.14.3          py312h06a4308_0
typer                     0.12.3                   pypi_0    pypi
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2024a                h04d1e81_0
unicodedata2              15.1.0          py312h5eee18b_0
urllib3                   2.2.2           py312h06a4308_0
wayland                   1.23.0               h5291e77_0    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
webencodings              0.5.1           py312h06a4308_2
websocket-client          1.8.0           py312h06a4308_0
werkzeug                  3.0.3           py312h06a4308_0
wheel                     0.43.0          py312h06a4308_0
widgetsnbextension        4.0.11             pyhd8ed1ab_0    conda-forge
wrapt                     1.16.0          py312h98912ed_0    conda-forge
xkeyboard-config          2.42                 h4ab18f5_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libx11               1.8.9                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxinerama          1.1.5                h27087fc_0    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h27cfd23_1007
xz                        5.4.6                h5eee18b_1
yaml                      0.2.5                h7b6447c_0
yarl                      1.9.4           py312h98912ed_0    conda-forge
zeromq                    4.3.5                h6a678d5_0
zipp                      3.19.2             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstandard                 0.22.0          py312h5b18bf6_1    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
```

### Environment info

```shell
active environment : python312
    active env location : /data/conda/envs/python312
            shell level : 2
       user config file : /home/x/.condarc
 populated config files : /data/conda/.condarc
                          /home/x/.condarc
          conda version : 24.5.0
    conda-build version : not installed
         python version : 3.12.3.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=zen2
                          __conda=24.5.0=0
                          __cuda=12.2=0
                          __glibc=2.28=0
                          __linux=4.18.0=0
                          __unix=0=0
       base environment : /data/conda  (writable)
      conda av data dir : /data/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/pytorch/linux-64
                          https://conda.anaconda.org/pytorch/noarch
                          https://conda.anaconda.org/nvidia/linux-64
                          https://conda.anaconda.org/nvidia/noarch
          package cache : /data/conda/pkgs
                          /home/x/.conda/pkgs
       envs directories : /data/conda/envs
                          /home/x/.conda/envs
               platform : linux-64
             user-agent : conda/24.5.0 requests/2.32.3 CPython/3.12.3 Linux/4.18.0-513.18.1.el8_9.x86_64 rhel/8.9 glibc/2.28 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
                UID:GID : 42016:42999
             netrc file : None
           offline mode : False
```

**Comment by ocefpaf** [comment]
You are mixing multiple channels it is likely the packages are not compatible with each other. See https://conda-forge.org/docs/user/tipsandtricks/#using-multiple-channels

**Comment by fgalarzajimenez** [comment]
Thanks! It was very useful. I tried conda install sqlite>=3.45 and the problem remained, so nice catch there.
