### ISSUE TITLE
 undefined symbol: sqlite3_deserialize

### ISSUE THREAD

**Issue by Flu09** [conda-forge/sqlite-feedstock#113]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue
```

python
Python 3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:03:24) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/user/conda-environments/scanpy_env2/lib/python3.12/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/user/conda-environments/scanpy_env2/lib/python3.12/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: /user/conda-environments/scanpy_env2/lib/python3.12/lib-dynload/_sqlite3.cpython-312-x86_64-linux-gnu.so: undefined symbol: sqlite3_deserialize
```

### Installed packages

```shell
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
absl-py                   2.1.0              pyhd8ed1ab_0    conda-forge
anndata                   0.10.8             pyhd8ed1ab_0    conda-forge
anyio                     4.4.0              pyhd8ed1ab_0    conda-forge
aom                       3.9.1                hac33072_0    conda-forge
arpack                    3.9.1           nompi_h77f6705_101    conda-forge
array-api-compat          1.8                pyhd8ed1ab_0    conda-forge
arrow                     1.3.0              pyhd8ed1ab_0    conda-forge
backoff                   2.2.1              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.3             pyha770c72_0    conda-forge
binutils_impl_linux-64    2.40                 ha1999f0_7    conda-forge
blessed                   1.19.1             pyhe4f9e05_2    conda-forge
blosc                     1.21.6               hef167b5_0    conda-forge
boto3                     1.35.0             pyhd8ed1ab_0    conda-forge
botocore                  1.35.0          pyge310_1234567_0    conda-forge
brotli                    1.1.0                hd590300_1    conda-forge
brotli-bin                1.1.0                hd590300_1    conda-forge
brotli-python             1.1.0           py312h30efb56_1    conda-forge
bwidget                   1.9.14               ha770c72_1    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.33.0               ha66036c_0    conda-forge
ca-certificates           2024.7.4             hbcca054_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.18.0               hebfffa5_3    conda-forge
certifi                   2024.7.4           pyhd8ed1ab_0    conda-forge
cffi                      1.17.0          py312h1671c18_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
chex                      0.1.86             pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contextlib2               21.6.0             pyhd8ed1ab_0    conda-forge
contourpy                 1.2.1           py312h8572e83_0    conda-forge
croniter                  1.4.1              pyhd8ed1ab_0    conda-forge
curl                      8.9.1                h18eb788_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
dateutils                 0.6.12                     py_0    conda-forge
dav1d                     1.2.1                hd590300_0    conda-forge
deepdiff                  7.0.1              pyhd8ed1ab_0    conda-forge
dnspython                 2.6.1              pyhd8ed1ab_1    conda-forge
docrep                    0.3.2              pyh44b312d_0    conda-forge
email-validator           2.2.0              pyhd8ed1ab_0    conda-forge
email_validator           2.2.0                hd8ed1ab_0    conda-forge
et_xmlfile                1.1.0              pyhd8ed1ab_0    conda-forge
etils                     1.9.2              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.2              pyhd8ed1ab_0    conda-forge
expat                     2.6.2                h59595ed_0    conda-forge
fastapi                   0.112.1            pyhd8ed1ab_0    conda-forge
fastapi-cli               0.0.5              pyhd8ed1ab_0    conda-forge
filelock                  3.15.4             pyhd8ed1ab_0    conda-forge
flax                      0.8.5              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_2    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.53.1          py312h41a817b_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
fsspec                    2024.6.1           pyhff2d567_0    conda-forge
gcc_impl_linux-64         14.1.0               h3c94d91_0    conda-forge
get-annotations           0.1.2              pyhd8ed1ab_0    conda-forge
gfortran_impl_linux-64    14.1.0               he4a1faa_0    conda-forge
glpk                      5.0                  h445213a_0    conda-forge
gmp                       6.3.0                hac33072_2    conda-forge
gmpy2                     2.1.5           py312h1d5cde6_1    conda-forge
graphite2                 1.3.13            h59595ed_1003    conda-forge
gsl                       2.7                  he838d99_0    conda-forge
gxx_impl_linux-64         14.1.0               h8d00ecb_0    conda-forge
h11                       0.14.0             pyhd8ed1ab_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
h5py                      3.11.0          nompi_py312hb7ab980_102    conda-forge
harfbuzz                  9.0.0                hda332d3_1    conda-forge
hdf5                      1.14.3          nompi_h4f84152_100    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
httpcore                  1.0.5              pyhd8ed1ab_0    conda-forge
httpx                     0.27.0             pyhd8ed1ab_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       75.1                 he02047a_0    conda-forge
idna                      3.7                pyhd8ed1ab_0    conda-forge
igraph                    0.10.13              hef0740d_0    conda-forge
importlib-metadata        8.2.0              pyha770c72_0    conda-forge
importlib_metadata        8.2.0                hd8ed1ab_0    conda-forge
importlib_resources       6.4.2              pyhd8ed1ab_0    conda-forge
inquirer                  3.1.4           py312h06a4308_0  
itsdangerous              2.2.0              pyhd8ed1ab_0    conda-forge
jax                       0.4.27             pyhd8ed1ab_0    conda-forge
jaxlib                    0.4.23          py312h6a678d5_0  
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
jmespath                  1.0.1              pyhd8ed1ab_0    conda-forge
joblib                    1.4.2              pyhd8ed1ab_0    conda-forge
kernel-headers_linux-64   2.6.32              he073ed8_17    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5           py312h8572e83_1    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.40                 hf3520f5_7    conda-forge
legacy-api-wrap           1.4                pyhd8ed1ab_1    conda-forge
leidenalg                 0.10.2          py312h30efb56_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20230802.1      cxx17_h59595ed_0    conda-forge
libaec                    1.1.3                h59595ed_0    conda-forge
libavif16                 1.1.1                h9b56c87_0    conda-forge
libblas                   3.9.0           23_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcblas                  3.9.0           23_linux64_openblas    conda-forge
libcurl                   8.9.1                hdb1bdb2_0    conda-forge
libdeflate                1.21                 h4bc722e_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-devel_linux-64     14.1.0             h5d3d1c9_100    conda-forge
libgcc-ng                 14.1.0               h77fa898_0    conda-forge
libgfortran-ng            14.1.0               h69a702a_0    conda-forge
libgfortran5              14.1.0               hc5f4f2c_0    conda-forge
libglib                   2.80.3               h315aac3_2    conda-forge
libgomp                   14.1.0               h77fa898_0    conda-forge
libhwloc                  2.11.1          default_hecaa2ac_1000    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           23_linux64_openblas    conda-forge
libleidenalg              0.11.1               h00ab1b0_0    conda-forge
libllvm14                 14.0.6               hcd5def8_4    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.27          pthreads_hac2b453_1    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libprotobuf               4.24.4               hf27288f_0    conda-forge
libsanitizer              14.1.0               hcba0ae0_0    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-devel_linux-64  14.1.0             h5d3d1c9_100    conda-forge
libstdcxx-ng              14.1.0               hc0a3c3a_0    conda-forge
libtiff                   4.6.0                h46a8edc_4    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libuv                     1.48.0               hd590300_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.16                 hd590300_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.12.7               he7c6b58_4    conda-forge
libzlib                   1.3.1                h4ab18f5_1    conda-forge
lightning                 2.0.9.post0        pyhd8ed1ab_0    conda-forge
lightning-cloud           0.5.70             pyhd8ed1ab_0    conda-forge
lightning-utilities       0.11.6             pyhd8ed1ab_0    conda-forge
llvmlite                  0.43.0          py312h9c5d478_0    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
make                      4.3                  hd18ef5c_1    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.5           py312h98912ed_0    conda-forge
matplotlib-base           3.9.2           py312h854627b_0    conda-forge
mdurl                     0.1.2              pyhd8ed1ab_0    conda-forge
ml-collections            0.1.1              pyhd8ed1ab_0    conda-forge
ml_dtypes                 0.4.0           py312h1d6d2e6_1    conda-forge
mpc                       1.3.1                hfe3b2da_0    conda-forge
mpfr                      4.2.1                h38ae2d0_2    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.8           py312h2492b07_0    conda-forge
mudata                    0.3.0              pyhd8ed1ab_0    conda-forge
multipledispatch          0.6.0              pyhd8ed1ab_1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
natsort                   8.4.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.5                  h59595ed_0    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
networkx                  3.3                pyhd8ed1ab_1    conda-forge
nomkl                     1.0                  h5ca1d4c_0    conda-forge
numba                     0.60.0          py312h83e6fd3_0    conda-forge
numpy                     1.26.4          py312heda63a1_0    conda-forge
numpyro                   0.15.2             pyhd8ed1ab_0    conda-forge
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openpyxl                  3.1.5           py312h98912ed_0    conda-forge
openssl                   3.3.1                h4bc722e_2    conda-forge
opt-einsum                3.3.0                hd8ed1ab_2    conda-forge
opt_einsum                3.3.0              pyhc1e730c_2    conda-forge
optax                     0.2.2              pyhd8ed1ab_1    conda-forge
orbax-checkpoint          0.4.4              pyhd8ed1ab_0    conda-forge
ordered-set               4.1.0              pyhd8ed1ab_0    conda-forge
orjson                    3.10.7          py312hf008fa9_0    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2           py312h1d6d2e6_1    conda-forge
pandoc                    3.3                  ha770c72_0    conda-forge
pango                     1.54.0               h4c5309f_1    conda-forge
patsy                     0.5.6              pyhd8ed1ab_0    conda-forge
pcre2                     10.44                hba22ea6_2    conda-forge
pillow                    10.4.0          py312h287a98d_0    conda-forge
pip                       24.2               pyhd8ed1ab_0    conda-forge
pixman                    0.43.2               h59595ed_0    conda-forge
protobuf                  4.24.4          py312h9a107e5_0    conda-forge
psutil                    6.0.0           py312h9a8786e_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pydantic                  1.10.17         py312h41a817b_0    conda-forge
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pyjwt                     2.9.0              pyhd8ed1ab_1    conda-forge
pynndescent               0.5.13             pyhff2d567_0    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pyro-api                  0.1.2              pyhd8ed1ab_0    conda-forge
pyro-ppl                  1.9.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pysqlite3                 0.5.3                    pypi_0    pypi
python                    3.12.1          hab00c5b_1_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-editor             1.0.4                      py_0    conda-forge
python-igraph             0.11.6          py312h0e1f547_0    conda-forge
python-multipart          0.0.9              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.12                    5_cp312    conda-forge
pytorch                   2.1.0           cpu_generic_py312h84c7d19_0    conda-forge
pytorch-lightning         2.4.0              pyhd8ed1ab_0    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.2           py312h41a817b_0    conda-forge
qhull                     2020.2               h434a139_5    conda-forge
r-abind                   1.4_5           r44hc72bb7e_1006    conda-forge
r-askpass                 1.2.0             r44hb1dbf0f_1    conda-forge
r-base                    4.4.1               h518d376_15    conda-forge
r-base64enc               0.1_3           r44hb1dbf0f_1007    conda-forge
r-bh                      1.84.0_0          r44hc72bb7e_1    conda-forge
r-bitops                  1.0_8             r44hdb488b9_0    conda-forge
r-bslib                   0.8.0             r44hc72bb7e_0    conda-forge
r-cachem                  1.1.0             r44hb1dbf0f_1    conda-forge
r-catools                 1.18.2            r44ha18555a_3    conda-forge
r-cli                     3.6.3             r44h0d4f4ea_1    conda-forge
r-cluster                 2.1.6             r44hbcb9c34_1    conda-forge
r-codetools               0.2_20            r44hc72bb7e_1    conda-forge
r-colorspace              2.1_1             r44hdb488b9_0    conda-forge
r-commonmark              1.9.1             r44hb1dbf0f_1    conda-forge
r-cowplot                 1.1.3             r44hc72bb7e_1    conda-forge
r-cpp11                   0.4.7             r44hc72bb7e_1    conda-forge
r-crayon                  1.5.3             r44hc72bb7e_1    conda-forge
r-crosstalk               1.2.1             r44hc72bb7e_1    conda-forge
r-curl                    5.2.1             r44h6b349a7_1    conda-forge
r-data.table              1.15.4            r44h5f06984_1    conda-forge
r-deldir                  2.0_4             r44hbcb9c34_1    conda-forge
r-digest                  0.6.36            r44ha18555a_1    conda-forge
r-dotcall64               1.1_1             r44hbcb9c34_1    conda-forge
r-dplyr                   1.1.4             r44h0d4f4ea_1    conda-forge
r-dqrng                   0.3.2             r44h0d4f4ea_1    conda-forge
r-ellipsis                0.3.2             r44hb1dbf0f_3    conda-forge
r-evaluate                0.24.0            r44hc72bb7e_1    conda-forge
r-fansi                   1.0.6             r44hb1dbf0f_1    conda-forge
r-farver                  2.1.2             r44ha18555a_1    conda-forge
r-fastdummies             1.7.4             r44hc72bb7e_0    conda-forge
r-fastmap                 1.2.0             r44ha18555a_1    conda-forge
r-fitdistrplus            1.2_1             r44hc72bb7e_0    conda-forge
r-fnn                     1.1.4             r44ha18555a_1    conda-forge
r-fontawesome             0.5.2             r44hc72bb7e_1    conda-forge
r-fs                      1.6.4             r44ha18555a_1    conda-forge
r-future                  1.34.0            r44h785f33e_0    conda-forge
r-future.apply            1.11.2            r44hc72bb7e_1    conda-forge
r-generics                0.1.3             r44hc72bb7e_3    conda-forge
r-ggplot2                 3.5.1             r44hc72bb7e_1    conda-forge
r-ggrepel                 0.9.5             r44h0d4f4ea_1    conda-forge
r-ggridges                0.5.6             r44hc72bb7e_1    conda-forge
r-globals                 0.16.3            r44hc72bb7e_1    conda-forge
r-glue                    1.7.0             r44hb1dbf0f_1    conda-forge
r-goftest                 1.2_3             r44hb1dbf0f_3    conda-forge
r-gplots                  3.1.3.1           r44hc72bb7e_1    conda-forge
r-gridextra               2.3             r44hc72bb7e_1006    conda-forge
r-gtable                  0.3.5             r44hc72bb7e_1    conda-forge
r-gtools                  3.9.5             r44hb1dbf0f_1    conda-forge
r-here                    1.0.1             r44hc72bb7e_3    conda-forge
r-hexbin                  1.28.3            r44hbcb9c34_2    conda-forge
r-highr                   0.11              r44hc72bb7e_1    conda-forge
r-htmltools               0.5.8.1           r44ha18555a_1    conda-forge
r-htmlwidgets             1.6.4             r44h785f33e_3    conda-forge
r-httpuv                  1.6.15            r44ha18555a_1    conda-forge
r-httr                    1.4.7             r44hc72bb7e_1    conda-forge
r-ica                     1.0_3             r44hc72bb7e_3    conda-forge
r-igraph                  2.0.3             r44h510f1ce_1    conda-forge
r-irlba                   2.3.5.1           r44h0d28552_3    conda-forge
r-isoband                 0.2.7             r44ha18555a_3    conda-forge
r-jquerylib               0.1.4             r44hc72bb7e_3    conda-forge
r-jsonlite                1.8.8             r44hb1dbf0f_1    conda-forge
r-kernsmooth              2.23_24           r44hc2011d3_1    conda-forge
r-knitr                   1.48              r44hc72bb7e_0    conda-forge
r-labeling                0.4.3             r44hc72bb7e_1    conda-forge
r-later                   1.3.2             r44ha18555a_1    conda-forge
r-lattice                 0.22_6            r44hb1dbf0f_1    conda-forge
r-lazyeval                0.2.2             r44hb1dbf0f_5    conda-forge
r-leiden                  0.4.3.1           r44hc72bb7e_1    conda-forge
r-lifecycle               1.0.4             r44hc72bb7e_1    conda-forge
r-listenv                 0.9.1             r44hc72bb7e_1    conda-forge
r-lmtest                  0.9_40            r44hbcb9c34_3    conda-forge
r-magrittr                2.0.3             r44hb1dbf0f_3    conda-forge
r-mass                    7.3_60.0.1        r44hb1dbf0f_1    conda-forge
r-matrix                  1.6_5             r44he966344_1    conda-forge
r-matrixstats             1.3.0             r44hb1dbf0f_1    conda-forge
r-memoise                 2.0.1             r44hc72bb7e_3    conda-forge
r-mgcv                    1.9_1             r44h0d28552_1    conda-forge
r-mime                    0.12              r44hb1dbf0f_3    conda-forge
r-miniui                  0.1.1.1         r44hc72bb7e_1005    conda-forge
r-munsell                 0.5.1             r44hc72bb7e_1    conda-forge
r-nlme                    3.1_165           r44hbcb9c34_1    conda-forge
r-openssl                 2.2.1             r44h5bbf899_0    conda-forge
r-parallelly              1.38.0            r44hdb488b9_0    conda-forge
r-patchwork               1.2.0             r44hc72bb7e_1    conda-forge
r-pbapply                 1.7_2             r44hc72bb7e_1    conda-forge
r-pillar                  1.9.0             r44hc72bb7e_2    conda-forge
r-pkgconfig               2.0.3             r44hc72bb7e_4    conda-forge
r-plotly                  4.10.4            r44hc72bb7e_1    conda-forge
r-plyr                    1.8.9             r44ha18555a_1    conda-forge
r-png                     0.1_8             r44h21f035c_2    conda-forge
r-polyclip                1.10_7            r44h0d4f4ea_0    conda-forge
r-progressr               0.14.0            r44hc72bb7e_1    conda-forge
r-promises                1.3.0             r44ha18555a_1    conda-forge
r-purrr                   1.0.2             r44hdb488b9_1    conda-forge
r-r6                      2.5.1             r44hc72bb7e_3    conda-forge
r-rann                    2.6.1             r44ha18555a_5    conda-forge
r-rappdirs                0.3.3             r44hb1dbf0f_3    conda-forge
r-rcolorbrewer            1.1_3             r44h785f33e_3    conda-forge
r-rcpp                    1.0.13            r44h0d4f4ea_0    conda-forge
r-rcppannoy               0.0.22            r44ha18555a_1    conda-forge
r-rcpparmadillo           14.0.0_1          r44hb424bfc_2    conda-forge
r-rcppeigen               0.3.4.0.1         r44hb424bfc_0    conda-forge
r-rcpphnsw                0.6.0             r44h0d4f4ea_1    conda-forge
r-rcppprogress            0.4.2             r44hc72bb7e_4    conda-forge
r-rcpptoml                0.2.2             r44ha18555a_2    conda-forge
r-reshape2                1.4.4             r44h0d4f4ea_4    conda-forge
r-reticulate              1.38.0            r44h0d4f4ea_1    conda-forge
r-rlang                   1.1.4             r44ha18555a_1    conda-forge
r-rmarkdown               2.28              r44hc72bb7e_0    conda-forge
r-rocr                    1.0_11            r44hc72bb7e_4    conda-forge
r-rprojroot               2.0.4             r44hc72bb7e_1    conda-forge
r-rspectra                0.16_2            r44hb424bfc_0    conda-forge
r-rtsne                   0.17              r44h4387864_1    conda-forge
r-sass                    0.4.9             r44ha18555a_1    conda-forge
r-scales                  1.3.0             r44hc72bb7e_1    conda-forge
r-scattermore             1.2               r44h0d4f4ea_3    conda-forge
r-sctransform             0.4.1             r44hb424bfc_1    conda-forge
r-seurat                  5.1.0             r44h0d4f4ea_1    conda-forge
r-seuratobject            5.0.2             r44h0d4f4ea_1    conda-forge
r-shiny                   1.9.1             r44h785f33e_0    conda-forge
r-sitmo                   2.0.2             r44h0d4f4ea_3    conda-forge
r-sourcetools             0.1.7_1           r44ha18555a_2    conda-forge
r-sp                      2.1_4             r44hdb488b9_1    conda-forge
r-spam                    2.10_0            r44h93271f8_1    conda-forge
r-spatstat.data           3.1_2             r44hc72bb7e_1    conda-forge
r-spatstat.explore        3.2_6             r44hdb488b9_1    conda-forge
r-spatstat.geom           3.2_9             r44hdb488b9_1    conda-forge
r-spatstat.random         3.2_3             r44h0d4f4ea_1    conda-forge
r-spatstat.sparse         3.1_0             r44hdb488b9_1    conda-forge
r-spatstat.utils          3.1_0             r44hdb488b9_0    conda-forge
r-stringi                 1.8.4             r44h33cde33_3    conda-forge
r-stringr                 1.5.1             r44h785f33e_1    conda-forge
r-survival                3.7_0             r44hdb488b9_1    conda-forge
r-sys                     3.4.2             r44hb1dbf0f_2    conda-forge
r-tensor                  1.5             r44hc72bb7e_1006    conda-forge
r-tibble                  3.2.1             r44hdb488b9_3    conda-forge
r-tidyr                   1.3.1             r44h0d4f4ea_1    conda-forge
r-tidyselect              1.2.1             r44hc72bb7e_1    conda-forge
r-tinytex                 0.52              r44hc72bb7e_0    conda-forge
r-utf8                    1.2.4             r44hb1dbf0f_1    conda-forge
r-uwot                    0.1.16            r44h0d4f4ea_1    conda-forge
r-vctrs                   0.6.5             r44h0d4f4ea_1    conda-forge
r-viridislite             0.4.2             r44hc72bb7e_2    conda-forge
r-withr                   3.0.1             r44hc72bb7e_0    conda-forge
r-xfun                    0.47              r44h0d4f4ea_0    conda-forge
r-xtable                  1.8_4             r44hc72bb7e_6    conda-forge
r-yaml                    2.3.10            r44hdb488b9_0    conda-forge
r-zoo                     1.8_12            r44hb1dbf0f_2    conda-forge
rav1e                     0.6.6                he8a937b_2    conda-forge
readchar                  4.2.0              pyhd8ed1ab_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
rich                      13.7.1             pyhd8ed1ab_0    conda-forge
s3transfer                0.10.2             pyhd8ed1ab_0    conda-forge
scanpy                    1.10.2             pyhd8ed1ab_0    conda-forge
scikit-learn              1.5.1           py312h775a589_0    conda-forge
scipy                     1.14.0          py312h499d17b_2    conda-forge
scvi-tools                1.1.5              pyhd8ed1ab_0    conda-forge
seaborn                   0.13.2               hd8ed1ab_2    conda-forge
seaborn-base              0.13.2             pyhd8ed1ab_2    conda-forge
sed                       4.8                  he412f7d_0    conda-forge
session-info              1.0.0              pyhd8ed1ab_0    conda-forge
setuptools                72.1.0             pyhd8ed1ab_0    conda-forge
shellingham               1.5.4              pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sleef                     3.6.1                h3400bea_1    conda-forge
snappy                    1.2.1                ha2e4443_0    conda-forge
sniffio                   1.3.1              pyhd8ed1ab_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
sparse                    0.15.4             pyhd8ed1ab_0    conda-forge
sqlite                    3.46.0               h6d4b2fc_0    conda-forge
starlette                 0.38.2             pyhd8ed1ab_0    conda-forge
starsessions              1.3.0           py312h06a4308_0  
statsmodels               0.14.2          py312h085067d_0    conda-forge
stdlib-list               0.10.0             pyhd8ed1ab_0    conda-forge
svt-av1                   2.1.2                hac33072_0    conda-forge
sympy                     1.13.2          pypyh2585a3b_103    conda-forge
sysroot_linux-64          2.12                he073ed8_17    conda-forge
tbb                       2021.12.0            h434a139_3    conda-forge
tensorstore               0.1.51          py312h3c940a5_0    conda-forge
texttable                 1.7.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.5.0              pyhc1e730c_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tktable                   2.10                 h8bc8fbc_6    conda-forge
toolz                     0.12.1             pyhd8ed1ab_0    conda-forge
torchmetrics              1.4.0.post0        pyhd8ed1ab_0    conda-forge
tqdm                      4.66.5             pyhd8ed1ab_0    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
typer                     0.12.4             pyhd8ed1ab_0    conda-forge
typer-slim                0.12.4             pyhd8ed1ab_0    conda-forge
typer-slim-standard       0.12.4               hd8ed1ab_0    conda-forge
types-python-dateutil     2.9.0.20240316     pyhd8ed1ab_0    conda-forge
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
umap-learn                0.5.6           py312h7900ff3_1    conda-forge
urllib3                   2.2.2              pyhd8ed1ab_1    conda-forge
uvicorn                   0.30.6          py312h7900ff3_0    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
websocket-client          1.8.0              pyhd8ed1ab_0    conda-forge
websockets                12.0            py312h98912ed_0    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
xarray                    2024.7.0           pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.9                hb711507_1    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-libxt                1.3.0                hd590300_1    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zipp                      3.20.0             pyhd8ed1ab_0    conda-forge
zlib                      1.3.1                h4ab18f5_1    conda-forge
zstandard                 0.23.0          py312h3483029_0    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
```

### Environment info

```shell
active environment : scanpy_env2
    active env location : /user/conda-environments/scanpy_env2
            shell level : 1
       user config file : /home/.condarc
 populated config files : /user/mambaforge/.condarc
                          /user/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.34=0
                          __linux=5.14.0=0
                          __unix=0=0
       base environment : /user/mambaforge  (writable)
      conda av data dir : /user/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /user/conda_cache
       envs directories : /user/conda-environments
                          /user/mambaforge/envs
                          /home/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.31.0 CPython/3.10.12 Linux/5.14.0-162.23.1.el9_1.x86_64 rocky/9.1 glibc/2.34
                UID:GID : 197417:1197417
             netrc file : None
           offline mode : False
```

**Comment by ocefpaf** [comment]
I can't reproduce that on Linux.

Also, you are mixing channels and pip installing `pysqlite3`, which is in conda-forge.  That  is likely the cause of the issue here.

**Comment by Flu09** [comment]
Sorry  I do not understand. I have this error when I installed through conda and it still remained after trying pip install pysqlite so I am not sure how to solve it.

**Comment by ocefpaf** [comment]
> Sorry I do not understand. I have this error when I installed through conda and it still remained after trying pip install pysqlite so I am not sure how to solve it.

You have many packages that are not from conda-forge and this one is from PyPI:

```
pysqlite3                 0.5.3                    pypi_0    pypi
```

We can't debug that or support it.  See https://conda-forge.org/docs/user/tipsandtricks/#using-multiple-channels

Please try a fresh env with all conda-forge packages and repost your environment list if the problem persistis.

**Comment by cunha17** [comment]
I was experiecing the same problem and I can confirm that updating all sqlite packages to conda-forge resolved the issue:

`conda install conda-forge::pysqlite3 conda-forge::sqlite conda-forge:libsqlite`
